name: Build and Push Docker Image
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: Login to Amazon ECR Private
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 941377159625.dkr.ecr.eu-north-1.amazonaws.com
      - name: Build Docker Image
        run: |
          docker build -t docker/imagine .
      - name: Tag Docker Image for Private ECR
        run: |
          docker tag docker/imagine:latest 941377159625.dkr.ecr.eu-north-1.amazonaws.com/docker/imagine:latest
      - name: Push Docker Image to ECR
        run: |
          docker push 941377159625.dkr.ecr.eu-north-1.amazonaws.com/docker/imagine:latest

      # - name: Fetch Existing Task Definition from AWS
      #   run: |
      #     aws ecs describe-task-definition --task-definition imagine-task \
      #     --query taskDefinition --output json > task-definition.json

      # - name: Update Task Definition with Latest Image
      #   run: |
      #     jq 'del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy) |
      #         .containerDefinitions[0].image="941377159625.dkr.ecr.eu-north-1.amazonaws.com/imagine:latest"' \
      #         task-definition.json > updated-task-def.json

      # - name: Register New Task Definition
      #   run: |
      #     NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://updated-task-def.json \
      #     --query 'taskDefinition.taskDefinitionArn' --output text --region eu-north-1)
      #     echo "TASK_DEF_ARN=${NEW_TASK_DEF_ARN}" >> $GITHUB_ENV

      # - name: Deploy New Task Definition to ECS
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      #   with:
      #     task-definition: "updated-task-def.json"
      #     service: imagine-service
      #     cluster: imagine-cluster
      #     wait-for-service-stability: true
